aws:
  accessKeyId: AKIAX5XSI5UT4M674AFL
  secretAccessKey: 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
  region: ap-south-1

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5433/nimesa
    username: postgres
    password: postgres
    hikari:
      connection-test-query: "SELECT 1"
      pool-name: finopsreportscronjob_pool
      minimum-idle: 1
      maximum-pool-size: 10
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
